# Generated by Django 5.2.14 on 2026-05-13 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_claim_number'),
        ('payments', '0002_remove_payment_payment_number_remove_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='claims.claim'),
        ),
    ]
