# Generated by Django 5.2.14 on 2026-05-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claimattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
